# Copyright 2017-Present Pivotal Software, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Set to true to enable all errands, false to disable all or leave blank to keep states the same.
enable_errands:

# The IaaS name for which stemcell to download. This must match the IaaS name
# within the stemcell to download, e.g. "vsphere", "aws", "azure", "google" must be lowercase.
#iaas_type: CHANGEME
iaas_type: azure

#git_private_key:
git_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJJwIBAAKCAgEAxPhblPzLniaeAsT1gzrFThrEkfEHfXVfxWLWEwcULkXaIdmd
  fCEMWGoFAyIQNbqk2sT1ECsVxH0iRJBtLbYr3VQETaI2J1+0FeXDJ9DNjQJM3HRf
  6dyUKMuT4lz/IlJERKbp9I9HeSuNN5aIjOS7Gyu0+6YkNMwLrDOxyXlqby8953mb
  ngmPFsQvt/8cw73FJO9DyI0HkBr7dnQytcSHwaw2PGQz5FgqmbOwTfK8AXkiS6zX
  ztnPpqcX7dLHGpeEHaXcKxQWEcHYEoScIcguvIeW4JHeMIU7Wqs9FF4BK35VseqZ
  va8hgZq2cdUt+Ebw6Hx+eVbw9xZD1SEJR/fMPmcj12ClxZVo2cZw/jVI19pBEZrJ
  JPQbL00k7/hhLWM9rW1cMbgUfvHmt7KuY0Fd+xfL2mEZmVP6JcwFg/CExhnI66nf
  m4+lgflw2RYOH25Kvd9BwsjkgjMyKi/IJHAXZfrhKTA2GTU2/G6LHl9ux/Mg+1OM
  B0nyftdQdgob2XBP5mnR3/OBWVGg9o6FXx+Szym93Ae/vYeK4R0QqWOFkpG2FFqV
  PGFDfLy7hODPWiKW6no8ICtdA1Z/8fgGmtj1in7b8kSExpHtAHna4RY9clv2KiAR
  6DBmIwOJ41yIY/xLqNA9j6IANytPKWmk27NTgaWp/e+aCUgw5OVegQGsgkUCAwEA
  AQKCAgBBDC/abP2ldeVazsaxltgP6iEefTXXBcsh+XjvAbh1a5YU9bPfiV51WFXd
  agNmawQER2US+NeQcy686+FSZkXoKtXc+YPezuk/Dgi7/mXTen39k+UU60Z2jnyB
  Fesf34EyFtlObX7SEkLpp6nitarg1zdGn+B3GyeDr/K3sYQnwbc02WE9+LQrdZC4
  t+Q89E/F2cpN0d08htyiis8wXf3jRMcIfKLydvdimQfRRic2aVWdHjCK3D2KMMZj
  QOeF7aGw1NR32YNMS/LacrbJJT3h/vkhoqp45ZbrY3+hWUYTof4U6n/pN4veLESy
  JQ+wXWUzseFmmwKq5sxx9x4EiV4GbVvNL4J+85m+MCDnuVCrR6QabXPD+t0iKy/W
  q1zhWaA/vmrLxvK9xkfW0iT4W7ykxiLqafJnxme4HErM9tFRsb31QqdXhSR5sQX5
  GMLfteqokufSpGaR7/kLmM+wEr0O9+zZXrhXBmyTPeL7yRVL0FAQCsoFgUcpaSso
  twTvupTv1rUyvgVT2ffrif6rSqUMDi2oJ5GPvzvzn3iUOaUSPLON9jrlPsSIVvpy
  mB9I8O4MWlgYQcVKX6Zw8vmP3VpuMHtMgMV9uGsBsXT7fWexmDfOx+LPwrBhb3sK
  ewXV0FYoNmACocuxfcfR3/wbTjZPF8xOkDmwtY3APFKMyWdC4QKCAQEA5MzWYu/w
  hO39Vqe9z7n6B/iLQQeYsugUmgpiDjyJnsA3H7gUBmw4b/QIbEHlTy+U3rPVmO84
  grI16gxxIYNp1UIvzZpkwBqOOGg6E0X7Psh7Fsyea5JYkhfwUrPYAcPXijLj1DHF
  7GFySRVVoIMMXt5WQLkima4Kx++VttWxC+zxxl9RMF/dxvQvqWPY7sFNQJQvlNp0
  JtojqT1qi9FvcJKOSnjqp1exHMOI1Y1VI1aMB+0sa+r1gG8XcUTZe//KGVn2mVlM
  N9smh8+wcdJPGrjogelpPNd3bBsCaNWxxEM1Wh1Q+5y7kmt8XL68D0AEuX1286EU
  qe2vfyKkHWgfLQKCAQEA3GLTY6Z/UeHaRgr+uS32RFDBqbmVEjdcsqFpGkERCAvY
  zTDt/lJ/9Rnh6YnhHjTH0irm57zHyP7O8NSRe4GGn8YiLgtM+KJl2A426cDikIs7
  lbKYbtwctNUPJz1I9dFsw+IZXP2A36NPC/GbUwWmVxLv46nhj/TXOYQUJJqLPDKq
  4aDiQXHGTg67orBcAdsjpfs+XDBMSjVWR+2OIwvkj3a9Yu8hJsGFECCPiUQo4bFQ
  ZtRkV9K2l2DFN/xzA3CbEULCzyPIofQdGeKhoitAx4Jqm0Pb5G1fQ99RrMiap6Uu
  b9277QL132Tqhj7nRniy/QxWk5i1mx9iFfgxHBieeQKCAQAhlqSeb6T6jsmTMBrg
  ZOf8xZMD3+6dzQ5BMucEOgTmBkfRYz+lVbvPS5707ZORVWXgb7wasHu2TB04F81/
  4v/la8sCvvitbviT9VEZRTvGEr5nMXDMT/aqs9L3ASnj0HFS+3eQziHFOuUBL52b
  a8GkJ7W32LXoo7E3eseayLIuEwHHYnTTyi8PpwdcMalGG6CQq3B0xMEqdvmnPbnn
  fr6CYzF6Y1fnays4EsiCuTXXczwpabsMuLiDu0tQuI/I8Vsk750RFBfpV0XHyEiZ
  3Qr53E1dzPtDEEqa1zg6Vay8KDWr3gPmfDLZIuhl4SZQgtBuvql4yJv0+ky6OEap
  foCdAoIBAA/potHDJ9ZFtHjyOkoso2dzXUhf+f+Ct9K+DNS0dgJauKC4M7b1Rf/w
  intOVU7VCMiICHwbCWHd5BtHfempBItsxvMEJd6d+zSKcjSWlMVTCE5awt7eTcRQ
  zfNLXYVCRdQu8x3fv/pl1ENMgqaP9d67o06Q6ZR3XULt4nZyIjOKhQQdlbib+nGQ
  ZsPsb/hCVmSZq3sEkb2Z9EzlPioRpcMmE66dDYu61VzAvRxwK3OAVgnWtBgTQtPT
  TOop9DP/YXLxmxdRwh7PfXps/ray4M6HACON1sa7jvFboo4TPfd02dGB9Ru75vzm
  UHi4+gIAnQvgZC/sCtDUh0SG0yTwMiECggEAIAsgYVve9tByX2CU/7kot8Kn5Y1q
  xgh9FYMvf88Ma+hnQXp7IDStGFIJEIrlJbEgHsYlI0bkHiMOLKXE1dWdCAq368R8
  HSSGUmuFs65tuWNmJx9BAsaxkSzyaxQzAWFsM+oaxwgpQ/rd0dkin2wX6iGjGz7y
  /m3n71Q77VDqGC2fn1caI43LrT0+Cul+D1VZKEpxThRxnRaCkCArB1mHf6BXgXDp
  cYl0bDhTQlQHr0t7pSaaKVtFxHyGzlZk7ITSEibsdLMo7R9rfCVn2a14Z53CVlPo
  iGew/KwmvnofdBNkVR8tHAh6WKSOt72oaZo7K1Gtk5787gM63mUTeChpYw==
  -----END RSA PRIVATE KEY-----

# Operations Manager
# ------------------------------
# Credentials for Operations Manager. These are used for uploading, staging,
# and deploying the product file on Operations Manager.
# Either opsman_client_id/opsman_client_secret or opsman_admin_username/opsman_admin_password needs to be specified.
# If you are using opsman_admin_username/opsman_admin_password, edit opsman_client_id/opsman_client_secret to be an empty value.
# If you are using opsman_client_id/opsman_client_secret, edit opsman_admin_username/opsman_admin_password to be an empty value.
#opsman_admin_username: CHANGEME
#opsman_admin_password: CHANGEME
#opsman_client_id: CHANGEME
#opsman_client_secret: CHANGEME
#opsman_domain_or_ip_address: CHANGEME
opsman_admin_username: admin
opsman_admin_password: Hills@20F
opsman_client_id: 
opsman_client_secret: 
opsman_domain_or_ip_address: az2.pvjp.cf

# Resource
# ------------------------------
# The token used to download the product file from Pivotal Network. Find this
# on your Pivotal Network profile page:
# https://network.pivotal.io/users/dashboard/edit-profile
pivnet_token: qYHaxpWgwa6n4BNjigks

# The globs regular expression for the PivNet resource to download the product
# release files. "*pivotal" is the default.
# For products such as ERT, it is recommended to use "cf*pivotal" to avoid the
# extra download of the SRT file in PCF 1.12.*
product_globs: "*pivotal"

# om-linux
# ------------------------------
# The name of the product on Pivotal Network. This is used to configure the
# resource that will fetch the product file.
#
# This can be found in the URL of the product page, e.g. for rabbitmq the URL
# is https://network.pivotal.io/products/pivotal-rabbitmq-service, and the
# product slug is 'pivotal-rabbitmq-service'.
#product_slug: 
product_slug: p-healthwatch

# The minor product version to track, as a regexp. To track 1.11.x of a product, this would be "^1\.11\..*$", as shown below.
#product_version_regex: ^1\.11\..*$
product_version_regex: ^1\.1\..*$
